# Generated by Django 5.1 on 2024-09-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_scrapingstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapingStatus',
        ),
    ]
